name: firebase_crud
description: "A Firebase CRUD package simplifying Firestore operations with optional logging and error tracking, designed for scalable and maintainable Flutter apps."
version: 0.0.8
homepage: https://github.com/riadhrahma/firebase_crud/tree/dev

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:

  cloud_firestore: ^5.4.4
  fake_cloud_firestore: ^3.0.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  logger: ^2.4.0
  meta: ^1.11.0
  mockito: ^5.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


